version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.14
    working_directory: ~/src/jsonrpc-go
    steps:
      - restore_cache:
          keys:
            - v1-pkg-cache
      - checkout
      - run: make setup
      - run: make install
      - save_cache:
          key: v1-pkg-cache
          paths:
            - "/go/pkg"

  lint:
    docker:
      - image: circleci/golang:1.14
    working_directory: ~/src/jsonrpc-go
    steps:
      - checkout
      - run: make setup
      - run: make lint

  test:
    docker:
      - image: circleci/golang:1.14
    working_directory: ~/src/jsonrpc-go
    environment:
      TEST_RESULTS: /tmp/test-results

    steps:
      - checkout
      - run: mkdir -p $TEST_RESULTS
      - run: make setup
      - run: go get github.com/jstemmer/go-junit-report
      - run:
          name: Run unit tests
          command: |
            trap "go-junit-report <${TEST_RESULTS}/go-test.out > ${TEST_RESULTS}/go-test-report.xml" EXIT
            go test -v ./... | tee ${TEST_RESULTS}/go-test.out
      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output
      - store_test_results:
          path: /tmp/test-results

  release:
    docker:
      - image: circleci/node:12.16.1
    steps:
      - checkout
      - add_ssh_keys
      - run: npm install conventional-changelog-conventionalcommits@4
      - run: npm install @semantic-release/changelog@5
      - run: npx semantic-release@17

  lint/commit:
    docker:
      - image: circleci/node:12.16.1
    steps:
      - checkout
      - run: npm install @commitlint/config-conventional@8.3.4
      - run: npx commitlint@8.3.5 --from $(git rev-parse origin/master) --to $CIRCLE_SHA1 --verbose

workflows:
  version: 2
  all:
    jobs:
      - build
      - lint
      - test
      - lint/commit:
          filters:
            branches:
              ignore:
                - master
      - release:
          requires:
            - build
            - lint
            - test
          filters:
            branches:
              only:
                - master
